#!/usr/bin/env python
# Author: Trae Horton
import sys
import argparse

parser = argparse.ArgumentParser(description='Perform Recon actions.')
parser.add_argument('--hash', dest='hash', help='Looks up file hash within VirusTotal.')
parser.add_argument('--banner', dest='banner', help='Shows the newest banner for Gabriel.')

args = parser.parse_args()
print(args.hash(args.banner))
