#!/usr/bin/env python
# Author: Trae Horton
import sys
import argparse

parser = argparse.ArgumentParser(description='Perform Recon actions.')
parser.add_argument('--hash', help='Looks up file hash within VirusTotal.')
parser.add_argument('--banner', help='Shows the newest banner for Gabriel.')

args = parser.parse_args()
print(args.accumulate(args.integers))
